export const SET_MENU = "SET_MENU";
export const SET_ASINS = "SET_ASINS";
export const GET_SETTING = 'GET_SETTING';
export const UPDATE_SETTING = 'UPDATE_SETTING';
export const SET_SETTING = 'SET_SETTING';
export const SET_VARIANT = 'SET_VARIANT';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const LOADING = "LOADING";
export const ERROR = "ERROR";
export const PROCESSING = "PROCESSING";

export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const IMPORT_PRODUCTS = "IMPORT_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const SELECT_PRODUCTS = "SELECT_PRODUCTS";
export const SAVE_VARIANT = "SAVE_VARIANT";

export const GET_HISOTRY = "GET_HISOTRY";
export const GET_HISOTRY_ITEMS = "GET_HISOTRY_ITEMS";

export const SHOW_SINGLE_PRODUCT_MODAL = "SHOW_SINGLE_PRODUCT_MODAL";
export const SHOW_MULTI_PRODUCT_MODAL = "SHOW_MULTI_PRODUCT_MODAL"
export const SHOW_DRAFT_DELETE_MODAL = "SHOW_DRAFT_DELETE_MODAL";
export const SHOW_DRAFT_IMPORT_MODAL = "SHOW_DRAFT_IMPORT_MODAL";
export const SHOW_PRODUCT_DELETE_MODAL = "SHOW_PRODUCT_DELETE_MODAL";
export const SHOW_HISTORY_ITEMS_MODAL = "SHOW_HISTORY_ITEMS_MODAL";
export const SHOW_HISTORY_MODAL = "SHOW_HISTORY_MODAL";
export const SHOW_ADD_IMAGE_MODAL = "SHOW_ADD_IMAGE_MODAL";
export const SHOW_EDIT_VARIANT_MODAL = "SHOW_EDIT_VARIANT_MODAL";

export const SHOW_ADD_PRODUCTS_MENU = "SHOW_ADD_PRODUCTS_MENU";
export const ADD_SELECT = "ADD_SELECT";
export const UPDATE_SELECT = "UPDATE_SELECT";
export const REMOVE_ALL_SELECT = "REMOVE_ALL_SELECT"
