import Head from 'next/head'
import SideBar from './SideBar'
import AddProductsDropDown from './AddProductsDropDown'
import SingleProductModal from './SingleProductModal'
import MultiProductModal from './MultiProductModal'
import { useState, useCallback } from 'react';
import { useRouter } from 'next/router';

export default function PageLayout({ children }) {

  const router = useRouter();
  const [showProductImportMenu, setShowProductImportMenu] = useState(false);
  const [showSingleProductModal, setShowSingleProductModal] = useState(false);
  const [showMultiProductModal, setShowMultiProductModal] = useState(false);

  const handleSingleProductImport = useCallback((productID) => {
    setShowSingleProductModal(false)

    router.push({
      pathname: '/predraft/[productID]',
      query: { productID }
    })  
  }, [router]);

  const handleMultiProductImport = useCallback(() => {
    
  }, []);

  const handleProductImportMenu = useCallback((menu) => {
    setShowProductImportMenu(false)

    if(menu == 1){
      setShowSingleProductModal(true)
    }else{
      setShowMultiProductModal(true)
    }
  }, []);

  return (
    <>
        <Head>
            <title>Auto Importer</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link
              rel="preload"
              href="/fonts/ProximaNova/ProximaNova-Bold.ttf"
              as="font"
              crossOrigin=""
            />
            <link
              rel="preload"
              href="/fonts/ProximaNova/ProximaNova-Regular.ttf"
              as="font"
              crossOrigin=""
            />
            <link
              rel="preload"
              href="/fonts/ProximaNova/ProximaNova-Medium.ttf"
              as="font"
              crossOrigin=""
            />
        </Head>
        <SideBar
          handleAddProducts={() => setShowProductImportMenu(!showProductImportMenu)}
        />
        <AddProductsDropDown
          show={showProductImportMenu}
          handleMenu={handleProductImportMenu}
        />   
        <SingleProductModal
          show={showSingleProductModal}
          handleClose={() => setShowSingleProductModal(!showSingleProductModal)}
          handleImport={handleSingleProductImport}
        />     
        <MultiProductModal
          show={showMultiProductModal}
          handleClose={() => setShowMultiProductModal(!showMultiProductModal)}        
          handleImport={handleMultiProductImport}
        />
        {children}        
    </>
  )
}
